version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    restart: always
    profiles: ["dev"]   # ✅ Only included when --profile dev is active
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  loki:
    image: grafana/loki:latest
    container_name: local_loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config/loki-config.yaml:/etc/loki/loki-config.yaml
      - /var/lib/loki:/var/lib/loki

  grafana:
    image: grafana/grafana:latest
    container_name: local_grafana
    restart: always
    ports:
      - "3200:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana

  auth:
    build: .
    container_name: local_auth
    restart: always
    depends_on:
      - loki
      - grafana
      # ⛔ Removed postgres from depends_on
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${PORT_AUTH}:${PORT_AUTH}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TOKEN_SECRET: ${TOKEN_SECRET}
      PORT_AUTH: ${PORT_AUTH}
      GRPC_PORT: ${GRPC_PORT}
      DOMAIN: ${DOMAIN}
      ENV: ${ENV}
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
  grafana-data: